#!/usr/bin/env python3
"""
Fuses a LoRA adapter into the base model and converts it to a format that can
be run locally with common tools (Ollama or a raw GGUF file), by invoking
mlx-lm's stable, public `mlx_lm.fuse` CLI (documented at
https://github.com/ml-explore/mlx-examples). `mlx_lm.fuse` supports an
`--export-gguf` flag that writes `model.gguf` directly into the save path,
which we use for the "gguf" format; for "ollama" we fuse to a plain MLX/
safetensors directory and write a Modelfile that points `ollama create` at it.

Usage: python3 export_model.py <model_dir> <adapter_dir> <output_dir> <format>
  <format> is "ollama" or "gguf"

Emits one JSON object per line to stdout, e.g.:
  {"type": "progress", "percent": 50, "message": "Fusing adapter into base model"}
  {"type": "done", "path": "/abs/path/to/export"}
  {"type": "error", "message": "human readable error"}

Real export only runs on Apple Silicon with `mlx-lm` installed. The Node
backend simulates this script's output shape when it is unavailable.
"""
import json
import os
import subprocess
import sys


def emit(obj):
    print(json.dumps(obj), flush=True)


def main():
    if len(sys.argv) < 5:
        emit({"type": "error", "message": "Usage: export_model.py <model_dir> <adapter_dir> <output_dir> <format>"})
        sys.exit(1)

    model_dir, adapter_dir, output_dir, fmt = sys.argv[1:5]

    try:
        import mlx_lm  # noqa: F401
    except ImportError:
        emit({
            "type": "error",
            "message": "mlx-lm is not installed on this machine. Run: pip install mlx-lm (requires Apple Silicon)",
        })
        sys.exit(2)

    os.makedirs(output_dir, exist_ok=True)

    cmd = [
        sys.executable,
        "-m",
        "mlx_lm.fuse",
        "--model",
        model_dir,
        "--adapter-path",
        adapter_dir,
        "--save-path",
        output_dir,
    ]
    if fmt == "gguf":
        cmd.append("--export-gguf")

    emit({"type": "progress", "percent": 15, "message": "Fusing your fine-tuned adapter into the base model"})

    try:
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1
        )
    except FileNotFoundError as exc:
        emit({"type": "error", "message": f"Could not launch mlx_lm.fuse: {exc}"})
        sys.exit(2)

    assert proc.stdout is not None
    for raw_line in proc.stdout:
        line = raw_line.strip()
        if line:
            emit({"type": "progress", "percent": 60, "message": line[:200]})

    returncode = proc.wait()
    if returncode != 0:
        emit({
            "type": "error",
            "message": f"mlx_lm.fuse exited with an error (code {returncode}). Check that your mlx-lm version supports --export-gguf.",
        })
        sys.exit(returncode)

    if fmt == "gguf":
        gguf_path = os.path.join(output_dir, "model.gguf")
        if not os.path.exists(gguf_path):
            emit({
                "type": "error",
                "message": "mlx_lm.fuse finished but no model.gguf was produced. Your installed mlx-lm version may not support --export-gguf.",
            })
            sys.exit(2)
        emit({"type": "progress", "percent": 95, "message": "GGUF file ready"})
        emit({"type": "done", "path": gguf_path})
        return

    # Ollama format: write a Modelfile beside the fused weights so the user
    # can run `ollama create my-model -f Modelfile` locally.
    modelfile_path = os.path.join(output_dir, "Modelfile")
    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(f"FROM {output_dir}\n")
        f.write('TEMPLATE """{{ .Prompt }}"""\n')
        f.write("# Generated by Local Fine-Tuning Studio\n")
        f.write("# Run: ollama create my-fine-tuned-model -f Modelfile\n")

    emit({"type": "progress", "percent": 95, "message": "Modelfile ready"})
    emit({"type": "done", "path": output_dir})


if __name__ == "__main__":
    main()
