#!/usr/bin/env python3
"""
Fuses a LoRA adapter into the base model and packages it so common local
tools can run it, by invoking mlx-lm's stable, public `mlx_lm.fuse` CLI
(https://github.com/ml-explore/mlx-lm).

Formats:
  gguf   -> a single model.gguf file (LM Studio, llama.cpp, Jan, Ollama).
            mlx-lm can only convert llama/mistral/mixtral model types to
            GGUF, and its converter writes f16 weights, so quantized base
            models must be dequantized during fusing.
  ollama -> for GGUF-capable model types: model.gguf + a Modelfile that
            points at it. For other architectures: a dequantized (f16)
            safetensors directory + a Modelfile pointing at the directory
            (requires a recent Ollama that can import safetensors weights).

Usage: python3 export_model.py <model_dir> <adapter_dir> <output_dir> <format>
  <format> is "ollama" or "gguf"

Emits one JSON object per line to stdout, e.g.:
  {"type": "progress", "percent": 50, "message": "Fusing adapter into base model"}
  {"type": "done", "path": "/abs/path/to/export"}
  {"type": "error", "message": "human readable error"}

Real export only runs on Apple Silicon with `mlx-lm` installed. The Node
backend simulates this script's output shape when it is unavailable.
"""
import json
import os
import subprocess
import sys

# mlx_lm.fuse --export-gguf only supports these model types (it raises a
# ValueError for anything else). Keep in sync with catalog.ts exportFormats.
GGUF_MODEL_TYPES = {"llama", "mistral", "mixtral"}


def emit(obj):
    print(json.dumps(obj), flush=True)


def read_model_config(model_dir):
    """Returns (model_type, is_quantized) from the model's config.json."""
    config_path = os.path.join(model_dir, "config.json")
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    except (OSError, ValueError):
        return None, False
    quantized = bool(config.get("quantization") or config.get("quantization_config"))
    return config.get("model_type"), quantized


def dequantize_flag():
    """The fuse CLI flag was renamed from --de-quantize to --dequantize;
    detect which spelling this mlx-lm version understands."""
    try:
        help_out = subprocess.run(
            [sys.executable, "-m", "mlx_lm.fuse", "--help"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if "--dequantize" in (help_out.stdout + help_out.stderr):
            return "--dequantize"
        if "--de-quantize" in (help_out.stdout + help_out.stderr):
            return "--de-quantize"
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "--dequantize"


def run_fuse(cmd):
    """Runs mlx_lm.fuse, streaming its output as progress. Returns
    (returncode, last_lines) where last_lines helps explain failures."""
    try:
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1
        )
    except FileNotFoundError as exc:
        return 1, [f"Could not launch mlx_lm.fuse: {exc}"]

    last_lines = []
    assert proc.stdout is not None
    for raw_line in proc.stdout:
        line = raw_line.strip()
        if line:
            last_lines.append(line)
            last_lines = last_lines[-5:]
            emit({"type": "progress", "percent": 60, "message": line[:200]})
    return proc.wait(), last_lines


def write_modelfile(output_dir, target, note):
    modelfile_path = os.path.join(output_dir, "Modelfile")
    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(f"FROM {target}\n")
        f.write("# Generated by Local Fine-Tuning Studio\n")
        f.write(f"# {note}\n")
        f.write("# To register with Ollama, run this in the unzipped folder:\n")
        f.write("#   ollama create my-fine-tuned-model -f Modelfile\n")


def cleanup_intermediate_weights(output_dir):
    """After a successful GGUF conversion the fused safetensors weights are
    redundant and large — remove them so downloads stay small."""
    for name in os.listdir(output_dir):
        if name.endswith(".safetensors") or name == "model.safetensors.index.json":
            try:
                os.remove(os.path.join(output_dir, name))
            except OSError:
                pass


def main():
    if len(sys.argv) < 5:
        emit({"type": "error", "message": "Usage: export_model.py <model_dir> <adapter_dir> <output_dir> <format>"})
        sys.exit(1)

    model_dir, adapter_dir, output_dir, fmt = sys.argv[1:5]

    try:
        import mlx_lm  # noqa: F401
    except ImportError:
        emit({
            "type": "error",
            "message": "mlx-lm is not installed on this machine. Run: pip install mlx-lm (requires Apple Silicon)",
        })
        sys.exit(2)

    model_type, quantized = read_model_config(model_dir)
    gguf_capable = model_type in GGUF_MODEL_TYPES

    if fmt == "gguf" and not gguf_capable:
        emit({
            "type": "error",
            "message": (
                f"This model's architecture ({model_type or 'unknown'}) can't be converted to GGUF yet — "
                "the converter only supports Llama, Mistral, and Mixtral families. "
                "Try the Ollama export format instead."
            ),
        })
        sys.exit(2)

    os.makedirs(output_dir, exist_ok=True)

    # GGUF conversion writes f16 weights, so quantized bases must be
    # dequantized while fusing. The Ollama safetensors-directory path also
    # needs f16 weights, because Ollama can't import MLX-quantized tensors.
    use_gguf = gguf_capable  # both "gguf" and "ollama" use GGUF when possible
    cmd = [
        sys.executable,
        "-m",
        "mlx_lm.fuse",
        "--model",
        model_dir,
        "--adapter-path",
        adapter_dir,
        "--save-path",
        output_dir,
    ]
    if quantized:
        cmd.append(dequantize_flag())
    if use_gguf:
        cmd.extend(["--export-gguf", "--gguf-path", "model.gguf"])

    emit({"type": "progress", "percent": 15, "message": "Fusing your fine-tuned adapter into the base model"})

    returncode, last_lines = run_fuse(cmd)
    if returncode != 0:
        detail = " | ".join(last_lines[-3:]) if last_lines else "no output"
        emit({
            "type": "error",
            "message": f"The model packaging step failed (mlx_lm.fuse exited with code {returncode}). Details: {detail[:400]}",
        })
        sys.exit(returncode or 1)

    if use_gguf:
        gguf_path = os.path.join(output_dir, "model.gguf")
        if not os.path.exists(gguf_path):
            # Very old mlx-lm versions ignore --gguf-path; check the default name.
            legacy = os.path.join(output_dir, "ggml-model-f16.gguf")
            if os.path.exists(legacy):
                os.replace(legacy, gguf_path)
            else:
                emit({
                    "type": "error",
                    "message": "Fusing finished but no GGUF file was produced. Try updating mlx-lm: pip install -U mlx-lm",
                })
                sys.exit(2)
        cleanup_intermediate_weights(output_dir)

        if fmt == "gguf":
            emit({"type": "progress", "percent": 95, "message": "GGUF file ready"})
            emit({"type": "done", "path": gguf_path})
            return

        # Ollama format on a GGUF-capable model: Modelfile + model.gguf.
        write_modelfile(output_dir, "./model.gguf", "The fine-tuned model, as a single GGUF file.")
        emit({"type": "progress", "percent": 95, "message": "Ollama Modelfile ready"})
        emit({"type": "done", "path": output_dir})
        return

    # Ollama format on a non-GGUF architecture: dequantized safetensors
    # directory + Modelfile pointing at the folder itself.
    write_modelfile(
        output_dir,
        ".",
        "Fine-tuned weights in safetensors format (needs a recent Ollama version).",
    )
    emit({"type": "progress", "percent": 95, "message": "Ollama Modelfile ready"})
    emit({"type": "done", "path": output_dir})


if __name__ == "__main__":
    main()
